version: '3.1'

services:

  mongo:
    image: mongo
    hostname: my-mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mynetwork
  rabbit:
    image: rabbitmq:3-management
    container_name: bunny
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mynetwork
  notification-server:
    image: notification-server 
    ports:
      - "5297:80"
      - "7082:443"
    networks:
      - mynetwork
    container_name: notification-server-container
  log-consumer:
    image: log-consumer
    ports:
      - "5216:80"
      - "7192:443"
    networks:
      - mynetwork
networks:
  mynetwork:
