global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "notification_server"
    static_configs:
      - targets: ["notification-server-container:5298"]
  - job_name: "log_consumer"
    static_configs:
      - targets: ["log-consumer:5217"]
  - job_name: "chat_gpt_service"
    static_configs:
      - targets:
          [
            "host.docker.internal:5001",
            "host.docker.internal:5000",
            "host.docker.internal:5002",
          ]
    # metrics_path: '/metrics'
