# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x03log\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n\nLogRequest\x12\x13\n\x0bserviceName\x18\x01 \x01(\t\x12\x16\n\x0eserviceMessage\x18\x02 \x01(\t\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1d\n\x08LogReply\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32\x41\n\x0cNotification\x12\x31\n\x0fSaveLogToRabbit\x12\x0f.log.LogRequest\x1a\r.log.LogReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGREQUEST']._serialized_start=51
  _globals['_LOGREQUEST']._serialized_end=150
  _globals['_LOGREPLY']._serialized_start=152
  _globals['_LOGREPLY']._serialized_end=181
  _globals['_NOTIFICATION']._serialized_start=183
  _globals['_NOTIFICATION']._serialized_end=248
# @@protoc_insertion_point(module_scope)
